---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: dev-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pradeepch82/tea:1.1
        ports:
        - containerPort: 80
